# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shortener.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("shortener.proto", :syntax => :proto3) do
    add_message "Shorten" do
    end
    add_message "Shorten.Request" do
      optional :url, :string, 1
    end
    add_message "Shorten.Response" do
      optional :token, :string, 1
    end
    add_message "Expand" do
    end
    add_message "Expand.Request" do
      optional :token, :string, 1
    end
    add_message "Expand.Response" do
      optional :url, :string, 1
    end
  end
end

Shorten = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Shorten").msgclass
Shorten::Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Shorten.Request").msgclass
Shorten::Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Shorten.Response").msgclass
Expand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Expand").msgclass
Expand::Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Expand.Request").msgclass
Expand::Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Expand.Response").msgclass
