# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: shortener.proto for package ''

require 'grpc'
require 'shortener_pb'

module ShortenerService
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'ShortenerService'

    rpc :Shorten, ::Shorten::Request, ::Shorten::Response
    rpc :Expand, ::Expand::Request, ::Expand::Response
  end

  Stub = Service.rpc_stub_class
end
